# Generated by Django 3.2.7 on 2021-10-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default='settings.MEDIA_ROOT/album_art/default.png', upload_to='album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='thumbnail',
            field=models.ImageField(default='settings.MEDIA_ROOT/artist/default.png', upload_to='artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(default='settings.MEDIA_ROOT/track/track.mp3', upload_to='track'),
        ),
    ]
