# Generated by Django 3.2.7 on 2021-10-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211009_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(default='/home/sm/Public/GrooveLife_Alpha/media/album_art/default.png', upload_to='album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='thumbnail',
            field=models.ImageField(default='/home/sm/Public/GrooveLife_Alpha/media/artist/default.png', upload_to='artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=models.SET(1), related_name='track', to='api.album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(default='/home/sm/Public/GrooveLife_Alpha/media/track/track.mp3', upload_to='track'),
        ),
    ]
