# Generated by Django 3.2.7 on 2021-10-30 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_likedsongs_likedsong'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likedsong',
            unique_together={('user', 'track')},
        ),
    ]
